typedef Document SVGDocument;

typedef DOMMatrix SVGMatrix;

typedef DOMException DOMError;

interface OverconstrainedError {
};

interface ReadableStream {
};

interface Transferable {
};

interface WindowProxy : Window {
};

//interface Capabilities {
//};
//
//interface Settings {
//};
//
//interface Dictionary {
//};
