interface ShadowRoot : DocumentFragment {
Selection? getSelection();
Element? elementFromPoint(double x, double y);
sequence<Element> elementsFromPoint(double x, double y);
CaretPosition? caretPositionFromPoint(double x, double y);
readonly attribute Element? activeElement;
readonly attribute Element host;
[TreatNullAs=EmptyString] attribute DOMString innerHTML;
readonly attribute StyleSheetList styleSheets;
};
partial interface Element {
ShadowRoot attachShadow(ShadowRootInit shadowRootInitDict);
readonly attribute Element? assignedSlot;
attribute DOMString slot;
readonly attribute ShadowRoot? shadowRoot;
};
dictionary ShadowRootInit {
ShadowRootMode mode;
};
enum ShadowRootMode {
"open", "closed"
};
partial interface Text {
readonly attribute Element? assignedSlot;
};
interface HTMLSlotElement : HTMLElement {
attribute DOMString name;
sequence<Node> getDistributedNodes();
};
partial dictionary EventInit {
boolean scoped = false;
};
partial interface Event {
readonly attribute object deepPath;
readonly attribute boolean scoped;
};
